### ISSUE TITLE
can't get this working 

### ISSUE THREAD

**Issue by Br3nda** [jonwaghorn/tracks#1]
i'm new to RoR. I just tried to install an instance of tracks on my laptop, following README

Here's what i tried....

sudo apt-get install mysql-server
wget http://github.com/downloads/jonwaghorn/tracks/tracks_anonymized_100510.sql.gz
gunzip tracks_anonymized_100510.sql.gz
mysql -u root -p < tracks_anonymized_100510.sql

sudo apt-get install ruby-bundler

 sudo bundle install
then i got an error: Could not find twitter-1.6.2 in any of the sources

i don't know what tracks uses twitter for,so i commented it out:
vim Gemfile
added a # infront of the twitter line

tried again:

 sudo bundle install
Installing hpricot (0.8.4) with native extensions /usr/lib/ruby/1.9.1/rubygems/installer.rb:556:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

```
    /usr/bin/ruby1.9.1 extconf.rb 
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:1:in `<main>'

a search for hpricot leads me to the project page, which says 
"Hpricot has ended. Please consider an alternative like nokogiri."

at which point i gave up....

**Comment by smozely** [comment]
I've just got further than that with my setup.

The project is expecting you to use RVM and have Ruby 1.9.2 installed with that.

Once RVM is installed correctly when you go into the tracks source folder it will force ruby 1.9.2.

From there bundle install worked correctly for me.

**Comment by Br3nda** [comment]
Is this still the current repo for this project? it's rails 2 -- has it been upgraded elsewhere?

**Comment by nickcoyne** [comment]
@Br3nda I started on a [Rails 3 fork](https://github.com/nickcoyne/tracks) a while back, but abandoned the idea when [trailforks.com](http://www.trailforks.com) took off.

**Comment by Br3nda** [comment]
Oh interesting. I use tracks.org.nz a lot. I thought i'd give a go at upgrading it - but rails 2 is a mission now.
